using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Globalization;
using System.Text;
using Architect.Build.SourceGenerator.Models;

namespace Architect.Build.SourceGenerator;

internal partial class BindableGenerator
{
    private static readonly TextInfo _textInfo = CultureInfo.InvariantCulture.TextInfo;

    private static string GenerateSourceCode(
        ClassInfo classInfo,
        // bool supportsPartialProps,
        CancellationToken token
    )
    {
        Debug.WriteLine($"[BindableGenerator.GenerateSourceCode] Generating source code for: {classInfo.Name}");
        token.ThrowIfCancellationRequested();
        StringBuilder builder = new();
        using StringWriter writer = new(builder, CultureInfo.InvariantCulture);
        using IndentedTextWriter source = new(writer, "\t");

        if (!classInfo.Modifiers.Contains("partial"))
            return string.Empty;

        token.ThrowIfCancellationRequested();
        WriteNamespaceAndUsings(source, classInfo);
        token.ThrowIfCancellationRequested();

        // WriteClassDeclaration(source, classInfo, supportsPartialProps, cancellationToken);
        WriteClassDeclaration(source, classInfo, token);
        return builder.ToString();
    }

    private static void WriteNamespaceAndUsings(IndentedTextWriter source, ClassInfo classInfo)
    {
        Debug.WriteLine("[BindableGenerator.WriteNamespaceAndUsings] Writing namespace and usings.");
        source.WriteLine("using Architect.UI.Data.Binding;");
        source.WriteLine("using System.Runtime.CompilerServices;");
        source.WriteLine();
        if (classInfo.Namespace.IsGlobal)
            return;

        Debug.WriteLine($"[BindableGenerator.WriteNamespaceAndUsings] Writing namespace: {classInfo.Namespace.Name}");
        source.WriteLine($"namespace {classInfo.Namespace.Name};");
    }

    private static void WriteClassDeclaration(
        IndentedTextWriter source,
        ClassInfo classInfo,
        // bool supportsPartialProps,
        CancellationToken token
    )
    {
        Debug.WriteLine($"[BindableGenerator.WriteClassDeclaration] Writing class declaration for {classInfo.Name}");
        token.ThrowIfCancellationRequested();
        source.WriteLine();
        source.WriteLine("// <auto-generated/>");
        source.WriteLine("#nullable enable");

        token.ThrowIfCancellationRequested();
        string classHeader = $"{string.Join(" ", classInfo.Modifiers)} class {classInfo.Name} : BindableObject";
        Debug.WriteLine($"[BindableGenerator.WriteClassDeclaration] Class header: {classHeader}");
        source.WriteLine(classHeader);
        source.WriteLine("{");
        source.Indent++;
        source.WriteLine("public override event PropertyChangedCallback PropertyChanged = delegate { };");
        token.ThrowIfCancellationRequested();

        // WriteProperties(source, classInfo, supportsPartialProps, cancellationToken);
        WriteProperties(source, classInfo, token);
        source.Indent--;
        source.WriteLine("}");
    }

    private static void WriteProperties(
        IndentedTextWriter source,
        ClassInfo classInfo,
        // bool supportsPartialProps,
        CancellationToken token
    )
    {
        
        Debug.WriteLine($"[BindableGenerator.WriteProperties] Writing {classInfo.Members.Count()} properties.");
        foreach (MemberInfo memberInfo in classInfo.Members)
        {
            token.ThrowIfCancellationRequested();
            Debug.WriteLine($"[BindableGenerator.WriteProperties] Writing property: {memberInfo.Name}");
            bool isPartial = memberInfo.Modifiers.Contains("partial");

            if (!isPartial && memberInfo.IsProperty)
            {
                Debug.WriteLine("[BindableGenerator.WriteProperties] Property is not partial. Skipping.");
                continue;
            }

            if (memberInfo.IsProperty)
            {
                if (isPartial)
                {
                    Debug.WriteLine(
                        $"[BindableGenerator.WriteProperties] Property {memberInfo.Name} is partial. Writing backing field: {memberInfo.BackingFieldName}");
                    source.WriteLine($"private {memberInfo.Type} {memberInfo.BackingFieldName};");
                }
                else
                {
                    Debug.WriteLine($"[BindableGenerator.WriteProperties] Property {memberInfo.Name} is not partial. Skipping.");
                    continue;
                }
            }

            string backingFieldName = isPartial
                ? memberInfo.BackingFieldName
                : memberInfo.Name;

            source.WriteLine();
            source.WriteLine("// <auto-generated/>");
            source.WriteLine("#nullable enable");
            string propertyName = isPartial
                ? memberInfo.Name
                : _textInfo.ToTitleCase(memberInfo.Name.TrimStart('_'));

            source.WriteLine(
                isPartial
                    ? $"{string.Join(" ", memberInfo.Modifiers)} {memberInfo.Type} {propertyName}"
                    : $"public {memberInfo.Type} {propertyName}"
            );

            source.WriteLine("{");
            source.Indent++;

            source.WriteLine($"get => GetProperty(ref {backingFieldName})!;");
            source.WriteLine($"set => SetProperty(ref {backingFieldName}, value);");

            source.Indent--;
            source.WriteLine("}");
            source.WriteLine();
        }


        WriteGetPropertyMethod(source, token);
        WriteSetPropertyMethod(source, token);
    }

    private static void WriteGetPropertyMethod(
        IndentedTextWriter source,
        CancellationToken token
    )
    {
        token.ThrowIfCancellationRequested();
        source.WriteLine("// <auto-generated/>");
        source.WriteLine("#nullable enable");

        token.ThrowIfCancellationRequested();
        source.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        source.WriteLine(
            "public override TValue? GetProperty<TValue>(ref TValue? field, TValue? initialValue = default) where TValue : default => field ??= initialValue;"
        );
        source.WriteLine();
    }

    private static void WriteSetPropertyMethod(
        IndentedTextWriter source,
        CancellationToken token
    )
    {
        token.ThrowIfCancellationRequested();
        source.WriteLine("// <auto-generated/>");
        source.WriteLine("#nullable enable");
        source.WriteLine(
            """public override void SetProperty<TValue>(ref TValue? field, TValue value, [CallerArgumentExpression(nameof(field))] string name = "") where TValue : default"""
        );
        source.WriteLine("{");

        source.Indent++;
        token.ThrowIfCancellationRequested();
        source.WriteLine("name = char.ToUpperInvariant(name[1]) + name[2..];");
        source.WriteLine("if (EqualityComparer<TValue>.Default.Equals(field, value))");

        token.ThrowIfCancellationRequested();
        source.Indent++;
        source.WriteLine("return;");
        source.Indent--;

        token.ThrowIfCancellationRequested();
        source.WriteLine();
        source.WriteLine("PropertyChanged.Invoke(name, field,  value);");
        source.WriteLine("field = value;");

        token.ThrowIfCancellationRequested();
        source.Indent--;
        source.WriteLine("}");
        source.WriteLine();
    }
}