using System.Reflection;

namespace Architect.Build.SourceGenerator;

internal partial class BindableGenerator
{
    private static readonly AssemblyName _assemblyName =
        typeof(BindableGenerator).Assembly.GetName();

    private static readonly string _generatedCodeAttribute =
        $"""global::System.CodeDom.Compiler.GeneratedCodeAttribute("{_assemblyName.Name}", "{_assemblyName.Version}")""";

    private static readonly string _bindableAttribute =
        $"""
         // <auto-generated/>
         #nullable enable

         namespace Roslyn.Generated;

         	[{_generatedCodeAttribute}]
         	[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
         	internal sealed class BindableAttribute : global::System.Attribute;

         """;

    private static readonly string _bindablePropertyAttribute =
        $"""
         // <auto-generated/>
         #nullable enable

         namespace Roslyn.Generated;

         	[{_generatedCodeAttribute}]
         	[global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field  , AllowMultiple = false)]
         	internal sealed class BindablePropertyAttribute : global::System.Attribute;

         """;
}